server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

datasource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/chapter_96?useUnicode=true&characterEncoding=UTF-8

datasource2:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  url: jdbc:mysql://localhost:3306/chapter_97?useUnicode=true&characterEncoding=UTF-8
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key-source: ${JWT_SECRET_KEY}